### ISSUE TITLE
Question regarding the DATASET

### ISSUE THREAD

**Issue by smiles724** [molML/MoleculeACE#4]
Hi, it is very helpful that you provided relevant datasets.

However, there is one thing I am concerned about. Do your benchmark dataset has clear relations of cliff molecules? In other words, can we know exactly which pair of molecules have close graph structures but significantly different properties?

Thanks,

**Comment by derekvantilborg** [comment]
Hi, we do not analyze individual activity cliff pairs in the paper because we were especially interested in dataset-level effects of the presence of activity cliffs. We do calculate them, however, to find all molecules that form activity cliff pairs, as we discuss in the paper. You can calculate and backtrack all individual activity cliff pairs using the functions found in MoleculeACE/benchmark/cliffs.py. We simply represent all pairs in a square matrix.

**Comment by smiles724** [comment]
Thanks, I noticed that in the code!
